name: Desplegar Frontend a AWS EKS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: "us-east-1"
  EKS_CLUSTER_NAME: "sanos-salvos-cluster"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Iniciar sesion en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Configurar Variables de Entorno (React/Vite)
      run: |
        echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env
        echo "VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }}" >> .env
        echo "VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }}" >> .env
        echo "VITE_AUTH0_AUDIENCE=${{ secrets.VITE_AUTH0_AUDIENCE }}" >> .env
        echo "VITE_CLOUDINARY_CLOUD_NAME=${{ secrets.VITE_CLOUDINARY_CLOUD_NAME }}" >> .env
        echo "VITE_CLOUDINARY_UPLOAD_PRESET=${{ secrets.VITE_CLOUDINARY_UPLOAD_PRESET }}" >> .env

    - name: Construir y subir imagen del Frontend a ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: sanos-salvos-frontend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY -a

    - name: Actualizar configuracion de kubeconfig
      run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

    - name: Desplegar en EKS
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        if [ -d "k8s" ]; then
          cd k8s
          for f in *.yaml; do
            sed -i "s|ECR_REGISTRY_PLACEHOLDER|$ECR_REGISTRY|g" $f
            sed -i "s|IMAGE_TAG_PLACEHOLDER|$IMAGE_TAG|g" $f
            kubectl apply -f $f
          done
        else
          echo "La carpeta k8s no se encontró en este repositorio."
        fi
